export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOADING_USER = 'LOADING_USER';
export const USER_LOADED = 'USER_LOADED';
export const SET_MESSAGE = 'SET_MESSAGE';

export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const LOAD_CATEGORY = 'LOAD_CATEGORY';
export const LOAD_ALL_CATEGORY = 'LOAD_ALL_CATEGORY';
export const IS_LOADING_CATEGORY = 'IS_LOADING_CATEGORY';

export const SAVE_MARKET = 'SAVE_MARKET';
export const UPDATE_MARKET = 'UPDATE_MARKET';
export const DELETE_MARKET = 'DELETE_MARKET';
export const LOAD_ALL_MARKET = 'LOAD_ALL_MARKET';
export const IS_LOADING_MARKET = 'IS_LOADING_MARKET';

export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_PRODUCT_DTO = 'LOAD_PRODUCT_DTO';
export const LOAD_ALL_PRODUCT = 'LOAD_ALL_PRODUCT';
export const IS_LOADING_PRODUCT = 'IS_LOADING_PRODUCT';

export const SAVE_PURCHASES = 'SAVE_PURCHASES';
export const UPDATE_PURCHASES = 'UPDATE_PURCHASES';
export const DELETE_PURCHASES = 'DELETE_PURCHASES';
export const LOAD_PURCHASES = 'LOAD_PURCHASES';
export const LOAD_PURCHASES_DTO = 'LOAD_PURCHASES_DTO';
export const LOAD_ALL_PURCHASES = 'LOAD_ALL_PURCHASES';
export const IS_LOADING_PURCHASES = 'IS_LOADING_PURCHASES';
export const ADD_ITEM_PURCHASES_UPDATE = 'ADD_ITEM_PURCHASES_UPDATE';

export const SAVE_USER = 'SAVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const LOAD_USER = 'LOAD_USER';
export const IS_LOADING_USER = 'IS_LOADING_USER';

export const SAVE_ENTRACEEXIT = 'SAVE_ENTRACEEXIT';
export const UPDATE_ENTRACEEXIT = 'UPDATE_ENTRACEEXIT';
export const DELETE_ENTRACEEXIT = 'DELETE_ENTRACEEXIT';
export const LOAD_ALL_ENTRACEEXIT = 'LOAD_ALL_ENTRACEEXIT';
export const IS_LOADING_ENTRACEEXIT = 'IS_LOADING_ENTRACEEXIT';

export const LOAD_STOCK = 'LOAD_STOCK';
export const LOAD_ALL_STOCK = 'LOAD_ALL_STOCK';
export const IS_LOADING_STOCK = 'IS_LOADING_STOCK';

export const COUNT_DASHBOARD = 'COUNT_DASHBOARD';
export const SUM_DASHBOARD = 'SUM_DASHBOARD';
export const TOP_DASHBOARD = 'TOP_DASHBOARD';
export const IS_LOADING_DASHBOARD = 'IS_LOADING_DASHBOARD';
